// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopFusion.Services.ProductAPI.Data;

#nullable disable

namespace ShopFusion.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240306134128_newDatas")]
    partial class newDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.Brands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Nature Land",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7426),
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Fortune",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7465),
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Patanjali",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7500),
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Fortune",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7534),
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Saffola",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7581),
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "Gowardhan",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7623),
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            BrandName = "ITC",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7655),
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            BrandName = "Flipkart Supermart",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7686),
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            BrandName = "Beyond Snack",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7718),
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            BrandName = "Cadbury",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7753),
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            BrandName = "Sunfeast",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7785),
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            BrandName = "UNIBIC",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7817),
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            BrandName = "Coca Cola",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7851),
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            BrandName = "Pepsi",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7882),
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            BrandName = "Red Bull",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7914),
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            BrandName = "Sting",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7946),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/09/06/2017/38deea34-44ce-4650-a1fb-60f1c0172feb.png?q=90",
                            CategoryName = "Dal's & Pulses",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7982),
                            IsActive = true,
                            MainCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/06/11/2023/bab3c31e-0be6-4f67-b9a6-cb341fa1f034.png?q=90",
                            CategoryName = "Ghee & Oils",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8016),
                            IsActive = true,
                            MainCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/05/07/2017/cd819684-9369-468b-895c-ef9b57b6b059.png?q=90",
                            CategoryName = "Atta & Flours",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8047),
                            IsActive = true,
                            MainCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/09/06/2017/ffad029d-5b1e-4de7-a91f-0bbe1803e197.png?q=90",
                            CategoryName = "Biscuits",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8077),
                            IsActive = true,
                            MainCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/05/07/2017/f5433b1c-955d-47e2-83a5-0dbfb240de13.png?q=90",
                            CategoryName = "Chips, Namkeen & Snacks",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8108),
                            IsActive = true,
                            MainCategoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryImage = "https://rukminim2.flixcart.com/www/100/100/promos/05/07/2017/93d975ff-8921-480a-afeb-13864520f568.png?q=90",
                            CategoryName = "Soft Drinks",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8141),
                            IsActive = true,
                            MainCategoryId = 2
                        });
                });

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MainCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MainCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7223),
                            IsActive = true,
                            MainCategoryName = "Staples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(7373),
                            IsActive = true,
                            MainCategoryName = "Snacks & Beverages"
                        });
                });

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8609),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/ke7ff680/pulses/z/m/x/500-kabuli-chana-kabuli-chana-natureland-organics-original-imafuy3hfkx4qw7d.jpeg?q=70",
                            ProductName = "Natureland Organics Kabuli Chana (Kabuli Buta) (Whole)  (500 g)",
                            ProductPrice = 126.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8651),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/kqpj4i80/pulses/r/a/z/1-arhar-dal-arhar-dal-natureland-organics-original-imag4npb8twt4dwz.jpeg?q=70",
                            ProductName = "Natureland Organics Yellow Toor/Arhar Dal (Harada Dali) (Split)  (1 kg)",
                            ProductPrice = 1299.0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8686),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/pulses/g/4/h/-original-imagpgzhcvgcyaxg.jpeg?q=70",
                            ProductName = "Tata Sampann White Urad Dal (Biri Dali) (Whole)  (1 kg)",
                            ProductPrice = 200.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8718),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/pulses/0/g/n/-original-imagsy58yzw47w8f.jpeg?q=70",
                            ProductName = "Natureland Organics Urad Dal (Biri Dali) (Split)  (1 kg)",
                            ProductPrice = 200.0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8750),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/280/280/xif0q/flour/d/u/z/-original-imagwhtwwm2ksbxe.jpeg?q=70",
                            ProductName = "PATANJALI Chakki Atta, Whole Wheat with Bran, Genhu ka Atta, Organic Flour (Whole-Gehuro otta)  (5 kg)",
                            ProductPrice = 222.0,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8788),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/kqidx8w0/flour/h/s/p/chakki-fresh-atta-whole-wheat-flour-fortune-original-imag4gb3ggvam3fg.jpeg?q=70",
                            ProductName = "Fortune Chakki Fresh Atta (Whole-Gehuro otta)  (10 kg)",
                            ProductPrice = 405.0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8834),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/edible-oil/g/g/k/-original-imaghuf2t32wgzhe.jpeg?q=70",
                            ProductName = "Saffola Gold Refined Cooking Rice Bran & Corn Blended Oil Pouch (Mishrita Tela)  (1 L)",
                            ProductPrice = 170.0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 6,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8916),
                            IsActive = true,
                            MainCategoryId = 1,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/ghee/x/9/q/750-cow-1-pouch-gowardhan-original-imagvp7fntadfgrx.jpeg?q=70",
                            ProductName = "Gowardhan Pure Cow Ghee 750 ml Pouch",
                            ProductPrice = 439.0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 12,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9083),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/cookie-biscuit/x/e/c/-original-imagnz5hhdcjpzcz.jpeg?q=70",
                            ProductName = "UNIBIC Cashew Badam Cookies  (300 g)",
                            ProductPrice = 48.0,
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 11,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9222),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/cookie-biscuit/d/v/l/64-orange-creme-1-sunfeast-bounce-original-imagmfuzdhxzh5t9.jpeg?q=70",
                            ProductName = "Sunfeast Bounce Orange Creme Biscotti  (20% Extra in Pack)  (63.2 g)",
                            ProductPrice = 9.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 10,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9333),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/cookie-biscuit/v/o/f/-original-imagwcjwu6gyaxqb.jpeg?q=70",
                            ProductName = "Cadbury Oreo Chocolate Flavour Biscuit Cream Sandwich  (131.25 g)",
                            ProductPrice = 36.0,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9371),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/l58iaa80/snack-savourie/k/r/x/-original-imagfybhffnh9uzz.jpeg?q=70",
                            ProductName = "Bingo Tedhe Medhe Masala Tadka (Namkeen)  (80 g)",
                            ProductPrice = 14.0,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 8,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9405),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/l58iaa80/snack-savourie/k/r/x/-original-imagfybhffnh9uzz.jpeg?q=70",
                            ProductName = "Flipkart Supermart Boondi (Bhakarwadi)  (300 g)",
                            ProductPrice = 14.0,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 7,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9438),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/l58iaa80/snack-savourie/k/r/x/-original-imagfybhffnh9uzz.jpeg?q=70",
                            ProductName = "Bingo Mad Angles Tomato Madness Chips  (66 g)",
                            ProductPrice = 17.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 9,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9697),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/chips/t/z/m/-original-imaghu8kqf7wtrh2.jpeg?q=70",
                            ProductName = "Beyond Snack Kerala Banana Salt and Black Pepper Chips  (75 g)",
                            ProductPrice = 40.0,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 13,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9731),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/kynb6vk0/aerated-drink/a/k/7/-original-imagau2nhx7aytga.jpeg?q=70",
                            ProductName = "Coca-Cola Diet Coke Can  (300 ml)",
                            ProductPrice = 36.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 14,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9763),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/j5y7gcw0-1/aerated-drink/h/z/r/2-25-na-mirinda-original-imaewj89mxyhdkrf.jpeg?q=70",
                            ProductName = "MiRiNDA Soft Drink PET Bottle  (2.25 L)",
                            ProductPrice = 77.0,
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 15,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9805),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/xif0q/energy-sport-drink-mix/r/n/c/-original-imagjt5c6m3hzqtd.jpeg?q=70",
                            ProductName = "Red Bull Original Energy Drink  (350 ml, Plain Flavored)",
                            ProductPrice = 146.0,
                            SubCategoryId = 12
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 16,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(9853),
                            IsActive = true,
                            MainCategoryId = 2,
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/416/416/jwqpocw0/energy-sport-drink-mix/e/h/y/250-na-sting-original-imafhcqqzh6vhmvt.jpeg?q=70",
                            ProductName = "Sting Energy Drink  (250 ml, Plain Flavored)",
                            ProductPrice = 26.0,
                            SubCategoryId = 12
                        });
                });

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.SubCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8184),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Toor Daal"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8220),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Urad Daal"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8255),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Wheat Atta"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8287),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Rava & Sooji"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8319),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Blended Oil"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8355),
                            IsActive = true,
                            MainCategoryId = 1,
                            SubCategoryName = "Ghee"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8388),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Cookies"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8432),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Cream Biscuits"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8467),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Namkeen"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8503),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Chips"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8537),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Cold Drinks"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 3, 6, 19, 11, 27, 24, DateTimeKind.Local).AddTicks(8571),
                            IsActive = true,
                            MainCategoryId = 2,
                            SubCategoryName = "Energy & Sports Drinks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
