// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopFusion.Services.ProductAPI.Data;

#nullable disable

namespace ShopFusion.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopFusion.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CategoryName = "Mens T-Shirts",
                            ProductDescription = "",
                            ProductImage = "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/q/7/a/l-men-regular-fit-printed-spread-collar-casual-shirt-dhruva-original-imagueaqamscp4es.jpeg?q=70&crop=false",
                            ProductName = "Men Regular Fit Checkered Spread Collar Casual Shirt",
                            ProductPrice = 850.0,
                            SubCategoryId = 1,
                            SubCategoryName = "RM CREATION"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CategoryName = "Mens T-Shirts",
                            ProductDescription = "",
                            ProductImage = "",
                            ProductName = "Men Regular Fit Printed Spread Collar Casual Shirt",
                            ProductPrice = 1299.0,
                            SubCategoryId = 1,
                            SubCategoryName = "RM CREATION"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CategoryName = "Mens T-Shirts",
                            ProductDescription = "",
                            ProductImage = "",
                            ProductName = "Men Regular Fit Printed Spread Collar Casual Shirt",
                            ProductPrice = 999.0,
                            SubCategoryId = 1,
                            SubCategoryName = "RM CREATION"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
